/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlindOracleAnalystInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getQueryDetails"
      | "getResult"
      | "owner"
      | "queries"
      | "queryCounter"
      | "respondToQuery"
      | "setVault"
      | "submitQuery"
      | "vault"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "QueryResponded" | "QuerySubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQueryDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "queries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queryCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "respondToQuery",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "submitQuery", values: [string]): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQueryDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "queries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "respondToQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace QueryRespondedEvent {
  export type InputTuple = [queryId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [queryId: bigint, timestamp: bigint];
  export interface OutputObject {
    queryId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuerySubmittedEvent {
  export type InputTuple = [
    queryId: BigNumberish,
    user: AddressLike,
    queryType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    queryId: bigint,
    user: string,
    queryType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    queryId: bigint;
    user: string;
    queryType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindOracleAnalyst extends BaseContract {
  connect(runner?: ContractRunner | null): BlindOracleAnalyst;
  waitForDeployment(): Promise<this>;

  interface: BlindOracleAnalystInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getQueryDetails: TypedContractMethod<
    [_queryId: BigNumberish],
    [
      [string, string, boolean] & {
        user: string;
        queryType: string;
        responded: boolean;
      }
    ],
    "view"
  >;

  getResult: TypedContractMethod<
    [_queryId: BigNumberish],
    [[string, boolean] & { result: string; responded: boolean }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  queries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        queryId: bigint;
        user: string;
        queryType: string;
        encryptedResult: string;
        responded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  queryCounter: TypedContractMethod<[], [bigint], "view">;

  respondToQuery: TypedContractMethod<
    [_queryId: BigNumberish, resultValue: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  setVault: TypedContractMethod<
    [_vaultAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  submitQuery: TypedContractMethod<[queryType: string], [bigint], "payable">;

  vault: TypedContractMethod<[], [string], "view">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQueryDetails"
  ): TypedContractMethod<
    [_queryId: BigNumberish],
    [
      [string, string, boolean] & {
        user: string;
        queryType: string;
        responded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [_queryId: BigNumberish],
    [[string, boolean] & { result: string; responded: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        queryId: bigint;
        user: string;
        queryType: string;
        encryptedResult: string;
        responded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "queryCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "respondToQuery"
  ): TypedContractMethod<
    [_queryId: BigNumberish, resultValue: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[_vaultAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitQuery"
  ): TypedContractMethod<[queryType: string], [bigint], "payable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "QueryResponded"
  ): TypedContractEvent<
    QueryRespondedEvent.InputTuple,
    QueryRespondedEvent.OutputTuple,
    QueryRespondedEvent.OutputObject
  >;
  getEvent(
    key: "QuerySubmitted"
  ): TypedContractEvent<
    QuerySubmittedEvent.InputTuple,
    QuerySubmittedEvent.OutputTuple,
    QuerySubmittedEvent.OutputObject
  >;

  filters: {
    "QueryResponded(uint256,uint256)": TypedContractEvent<
      QueryRespondedEvent.InputTuple,
      QueryRespondedEvent.OutputTuple,
      QueryRespondedEvent.OutputObject
    >;
    QueryResponded: TypedContractEvent<
      QueryRespondedEvent.InputTuple,
      QueryRespondedEvent.OutputTuple,
      QueryRespondedEvent.OutputObject
    >;

    "QuerySubmitted(uint256,address,string,uint256)": TypedContractEvent<
      QuerySubmittedEvent.InputTuple,
      QuerySubmittedEvent.OutputTuple,
      QuerySubmittedEvent.OutputObject
    >;
    QuerySubmitted: TypedContractEvent<
      QuerySubmittedEvent.InputTuple,
      QuerySubmittedEvent.OutputTuple,
      QuerySubmittedEvent.OutputObject
    >;
  };
}
