/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlindOracleVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetToken"
      | "complianceRequired"
      | "confidentialProtocolId"
      | "createVault"
      | "deposit"
      | "getBalance"
      | "getDepositCount"
      | "getEncryptedBalance"
      | "getTotalVaults"
      | "hasVault"
      | "isAllowed"
      | "owner"
      | "setComplianceRequired"
      | "setUserAllowed"
      | "totalVaults"
      | "vaultIndex"
      | "vaults"
      | "withdraw"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceRequiredSet"
      | "Deposit"
      | "UserAllowedSet"
      | "VaultCreated"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assetToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "complianceRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setComplianceRequired",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaultIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vaults", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "assetToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "complianceRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDepositCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace ComplianceRequiredSetEvent {
  export type InputTuple = [required: boolean];
  export type OutputTuple = [required: boolean];
  export interface OutputObject {
    required: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAllowedSetEvent {
  export type InputTuple = [user: AddressLike, allowed: boolean];
  export type OutputTuple = [user: string, allowed: boolean];
  export interface OutputObject {
    user: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindOracleVault extends BaseContract {
  connect(runner?: ContractRunner | null): BlindOracleVault;
  waitForDeployment(): Promise<this>;

  interface: BlindOracleVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetToken: TypedContractMethod<[], [string], "view">;

  complianceRequired: TypedContractMethod<[], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createVault: TypedContractMethod<
    [initialBalance: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getDepositCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEncryptedBalance: TypedContractMethod<[], [string], "view">;

  getTotalVaults: TypedContractMethod<[], [bigint], "view">;

  hasVault: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isAllowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setComplianceRequired: TypedContractMethod<
    [required: boolean],
    [void],
    "nonpayable"
  >;

  setUserAllowed: TypedContractMethod<
    [user: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  totalVaults: TypedContractMethod<[], [bigint], "view">;

  vaultIndex: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  vaults: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        user: string;
        balance: string;
        plaintextBalance: bigint;
        depositCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "complianceRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<[initialBalance: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDepositCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalVaults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVault"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setComplianceRequired"
  ): TypedContractMethod<[required: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserAllowed"
  ): TypedContractMethod<
    [user: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalVaults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vaultIndex"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, boolean] & {
        user: string;
        balance: string;
        plaintextBalance: bigint;
        depositCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ComplianceRequiredSet"
  ): TypedContractEvent<
    ComplianceRequiredSetEvent.InputTuple,
    ComplianceRequiredSetEvent.OutputTuple,
    ComplianceRequiredSetEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "UserAllowedSet"
  ): TypedContractEvent<
    UserAllowedSetEvent.InputTuple,
    UserAllowedSetEvent.OutputTuple,
    UserAllowedSetEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "ComplianceRequiredSet(bool)": TypedContractEvent<
      ComplianceRequiredSetEvent.InputTuple,
      ComplianceRequiredSetEvent.OutputTuple,
      ComplianceRequiredSetEvent.OutputObject
    >;
    ComplianceRequiredSet: TypedContractEvent<
      ComplianceRequiredSetEvent.InputTuple,
      ComplianceRequiredSetEvent.OutputTuple,
      ComplianceRequiredSetEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "UserAllowedSet(address,bool)": TypedContractEvent<
      UserAllowedSetEvent.InputTuple,
      UserAllowedSetEvent.OutputTuple,
      UserAllowedSetEvent.OutputObject
    >;
    UserAllowedSet: TypedContractEvent<
      UserAllowedSetEvent.InputTuple,
      UserAllowedSetEvent.OutputTuple,
      UserAllowedSetEvent.OutputObject
    >;

    "VaultCreated(address,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "Withdrawal(address,uint256,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
