/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlindOracleFHEVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "complianceRequired"
      | "confidentialProtocolId"
      | "createPrivateVault"
      | "depositPrivate"
      | "getEncryptedBalance"
      | "getEncryptedBalanceHandle"
      | "getPrivateOperationCount"
      | "getPublicVaultMetadata"
      | "grantBalanceAccess"
      | "hasPrivateVault"
      | "isAllowed"
      | "owner"
      | "setComplianceRequired"
      | "setUserAllowed"
      | "totalVaults"
      | "vaultIndex"
      | "withdrawPrivate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BalanceAccessGranted"
      | "ComplianceRequiredSet"
      | "PrivateDeposit"
      | "PrivateVaultCreated"
      | "PrivateWithdrawal"
      | "UserAllowedSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "complianceRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPrivateVault",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPrivate",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalanceHandle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrivateOperationCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicVaultMetadata",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantBalanceAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPrivateVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setComplianceRequired",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserAllowed",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaultIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPrivate",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "complianceRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPrivateVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPrivate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalanceHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrivateOperationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicVaultMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantBalanceAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPrivateVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setComplianceRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPrivate",
    data: BytesLike
  ): Result;
}

export namespace BalanceAccessGrantedEvent {
  export type InputTuple = [user: AddressLike, viewer: AddressLike];
  export type OutputTuple = [user: string, viewer: string];
  export interface OutputObject {
    user: string;
    viewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceRequiredSetEvent {
  export type InputTuple = [required: boolean];
  export type OutputTuple = [required: boolean];
  export interface OutputObject {
    required: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateDepositEvent {
  export type InputTuple = [
    user: AddressLike,
    encryptedBalanceHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    encryptedBalanceHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    encryptedBalanceHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateVaultCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    encryptedBalanceHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    encryptedBalanceHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    encryptedBalanceHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateWithdrawalEvent {
  export type InputTuple = [
    user: AddressLike,
    encryptedBalanceHandle: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    encryptedBalanceHandle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    encryptedBalanceHandle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAllowedSetEvent {
  export type InputTuple = [user: AddressLike, allowed: boolean];
  export type OutputTuple = [user: string, allowed: boolean];
  export interface OutputObject {
    user: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindOracleFHEVault extends BaseContract {
  connect(runner?: ContractRunner | null): BlindOracleFHEVault;
  waitForDeployment(): Promise<this>;

  interface: BlindOracleFHEVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  complianceRequired: TypedContractMethod<[], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createPrivateVault: TypedContractMethod<
    [encryptedInitialBalance: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  depositPrivate: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEncryptedBalance: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getEncryptedBalanceHandle: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getPrivateOperationCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getPublicVaultMetadata: TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, string] & {
        vaultOwner: string;
        operationCount: bigint;
        encryptedBalanceHandle: string;
      }
    ],
    "view"
  >;

  grantBalanceAccess: TypedContractMethod<
    [viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  hasPrivateVault: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isAllowed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setComplianceRequired: TypedContractMethod<
    [required: boolean],
    [void],
    "nonpayable"
  >;

  setUserAllowed: TypedContractMethod<
    [user: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  totalVaults: TypedContractMethod<[], [bigint], "view">;

  vaultIndex: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  withdrawPrivate: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "complianceRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPrivateVault"
  ): TypedContractMethod<
    [encryptedInitialBalance: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositPrivate"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBalanceHandle"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPrivateOperationCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPublicVaultMetadata"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, string] & {
        vaultOwner: string;
        operationCount: bigint;
        encryptedBalanceHandle: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantBalanceAccess"
  ): TypedContractMethod<[viewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasPrivateVault"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setComplianceRequired"
  ): TypedContractMethod<[required: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserAllowed"
  ): TypedContractMethod<
    [user: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalVaults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vaultIndex"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawPrivate"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BalanceAccessGranted"
  ): TypedContractEvent<
    BalanceAccessGrantedEvent.InputTuple,
    BalanceAccessGrantedEvent.OutputTuple,
    BalanceAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceRequiredSet"
  ): TypedContractEvent<
    ComplianceRequiredSetEvent.InputTuple,
    ComplianceRequiredSetEvent.OutputTuple,
    ComplianceRequiredSetEvent.OutputObject
  >;
  getEvent(
    key: "PrivateDeposit"
  ): TypedContractEvent<
    PrivateDepositEvent.InputTuple,
    PrivateDepositEvent.OutputTuple,
    PrivateDepositEvent.OutputObject
  >;
  getEvent(
    key: "PrivateVaultCreated"
  ): TypedContractEvent<
    PrivateVaultCreatedEvent.InputTuple,
    PrivateVaultCreatedEvent.OutputTuple,
    PrivateVaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PrivateWithdrawal"
  ): TypedContractEvent<
    PrivateWithdrawalEvent.InputTuple,
    PrivateWithdrawalEvent.OutputTuple,
    PrivateWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "UserAllowedSet"
  ): TypedContractEvent<
    UserAllowedSetEvent.InputTuple,
    UserAllowedSetEvent.OutputTuple,
    UserAllowedSetEvent.OutputObject
  >;

  filters: {
    "BalanceAccessGranted(address,address)": TypedContractEvent<
      BalanceAccessGrantedEvent.InputTuple,
      BalanceAccessGrantedEvent.OutputTuple,
      BalanceAccessGrantedEvent.OutputObject
    >;
    BalanceAccessGranted: TypedContractEvent<
      BalanceAccessGrantedEvent.InputTuple,
      BalanceAccessGrantedEvent.OutputTuple,
      BalanceAccessGrantedEvent.OutputObject
    >;

    "ComplianceRequiredSet(bool)": TypedContractEvent<
      ComplianceRequiredSetEvent.InputTuple,
      ComplianceRequiredSetEvent.OutputTuple,
      ComplianceRequiredSetEvent.OutputObject
    >;
    ComplianceRequiredSet: TypedContractEvent<
      ComplianceRequiredSetEvent.InputTuple,
      ComplianceRequiredSetEvent.OutputTuple,
      ComplianceRequiredSetEvent.OutputObject
    >;

    "PrivateDeposit(address,bytes32,uint256)": TypedContractEvent<
      PrivateDepositEvent.InputTuple,
      PrivateDepositEvent.OutputTuple,
      PrivateDepositEvent.OutputObject
    >;
    PrivateDeposit: TypedContractEvent<
      PrivateDepositEvent.InputTuple,
      PrivateDepositEvent.OutputTuple,
      PrivateDepositEvent.OutputObject
    >;

    "PrivateVaultCreated(address,bytes32,uint256)": TypedContractEvent<
      PrivateVaultCreatedEvent.InputTuple,
      PrivateVaultCreatedEvent.OutputTuple,
      PrivateVaultCreatedEvent.OutputObject
    >;
    PrivateVaultCreated: TypedContractEvent<
      PrivateVaultCreatedEvent.InputTuple,
      PrivateVaultCreatedEvent.OutputTuple,
      PrivateVaultCreatedEvent.OutputObject
    >;

    "PrivateWithdrawal(address,bytes32,uint256)": TypedContractEvent<
      PrivateWithdrawalEvent.InputTuple,
      PrivateWithdrawalEvent.OutputTuple,
      PrivateWithdrawalEvent.OutputObject
    >;
    PrivateWithdrawal: TypedContractEvent<
      PrivateWithdrawalEvent.InputTuple,
      PrivateWithdrawalEvent.OutputTuple,
      PrivateWithdrawalEvent.OutputObject
    >;

    "UserAllowedSet(address,bool)": TypedContractEvent<
      UserAllowedSetEvent.InputTuple,
      UserAllowedSetEvent.OutputTuple,
      UserAllowedSetEvent.OutputObject
    >;
    UserAllowedSet: TypedContractEvent<
      UserAllowedSetEvent.InputTuple,
      UserAllowedSetEvent.OutputTuple,
      UserAllowedSetEvent.OutputObject
    >;
  };
}
