/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PrivateAIInferenceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getResponse"
      | "inferenceFee"
      | "owner"
      | "queries"
      | "queryCounter"
      | "respondToQuery"
      | "setFee"
      | "submitQuery"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FeeUpdated" | "QueryResponded" | "QuerySubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResponse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "inferenceFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "queries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queryCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "respondToQuery",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitQuery",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inferenceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "queries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "respondToQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QueryRespondedEvent {
  export type InputTuple = [queryId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [queryId: bigint, timestamp: bigint];
  export interface OutputObject {
    queryId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuerySubmittedEvent {
  export type InputTuple = [
    queryId: BigNumberish,
    user: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [queryId: bigint, user: string, timestamp: bigint];
  export interface OutputObject {
    queryId: bigint;
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateAIInference extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateAIInference;
  waitForDeployment(): Promise<this>;

  interface: PrivateAIInferenceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getResponse: TypedContractMethod<
    [_queryId: BigNumberish],
    [[string, boolean] & { encryptedResponse: string; responded: boolean }],
    "view"
  >;

  inferenceFee: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  queries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint] & {
        queryId: bigint;
        user: string;
        encryptedResponse: string;
        responded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  queryCounter: TypedContractMethod<[], [bigint], "view">;

  respondToQuery: TypedContractMethod<
    [_queryId: BigNumberish, inputResponse: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  setFee: TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;

  submitQuery: TypedContractMethod<
    [inputQuery: BytesLike[], inputProof: BytesLike[]],
    [bigint],
    "payable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getResponse"
  ): TypedContractMethod<
    [_queryId: BigNumberish],
    [[string, boolean] & { encryptedResponse: string; responded: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "inferenceFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, boolean, bigint] & {
        queryId: bigint;
        user: string;
        encryptedResponse: string;
        responded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "queryCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "respondToQuery"
  ): TypedContractMethod<
    [_queryId: BigNumberish, inputResponse: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitQuery"
  ): TypedContractMethod<
    [inputQuery: BytesLike[], inputProof: BytesLike[]],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "QueryResponded"
  ): TypedContractEvent<
    QueryRespondedEvent.InputTuple,
    QueryRespondedEvent.OutputTuple,
    QueryRespondedEvent.OutputObject
  >;
  getEvent(
    key: "QuerySubmitted"
  ): TypedContractEvent<
    QuerySubmittedEvent.InputTuple,
    QuerySubmittedEvent.OutputTuple,
    QuerySubmittedEvent.OutputObject
  >;

  filters: {
    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "QueryResponded(uint256,uint256)": TypedContractEvent<
      QueryRespondedEvent.InputTuple,
      QueryRespondedEvent.OutputTuple,
      QueryRespondedEvent.OutputObject
    >;
    QueryResponded: TypedContractEvent<
      QueryRespondedEvent.InputTuple,
      QueryRespondedEvent.OutputTuple,
      QueryRespondedEvent.OutputObject
    >;

    "QuerySubmitted(uint256,address,uint256)": TypedContractEvent<
      QuerySubmittedEvent.InputTuple,
      QuerySubmittedEvent.OutputTuple,
      QuerySubmittedEvent.OutputObject
    >;
    QuerySubmitted: TypedContractEvent<
      QuerySubmittedEvent.InputTuple,
      QuerySubmittedEvent.OutputTuple,
      QuerySubmittedEvent.OutputObject
    >;
  };
}
